### ISSUE TITLE
Airfield is always $5 regardless of setting

### ISSUE THREAD

**Issue by Jersukai** [gta-chaos-mod/ChaosModComplementaries#2]

**Comment by Lordmau5** [comment]
The way that fix works is that it checks all pickups in the game and when it finds one that costs $80.000 and is of a specific time it will set it's price to $5.

This will be saved when the game is saved, so it will not be changed back.

Can you try doing the mission before unlocking the buy pickup with the setting turned off?
Because I remember during testing it worked fine that way.

**Comment by Jersukai** [comment]
I have tested I think all possible cases. I used this save I downloaded
[GTASAsf1.zip](https://github.com/gta-chaos-mod/ChaosModComplementaries/files/9541522/GTASAsf1.zip)

**Comment by Lordmau5** [comment]
Ah I found the issue.

Seems like I check for "CheapAir**strip**" in the code but the config has an option called "CheapAir**port**"

Will be fixed in v1.0.1
